version: 2
groups:
  code-review:
    approve_by_comment:
      enabled: true
      approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
      reject_regex: '^(Rejected|:-1:)'
    required: 1
    reset_on_push:
      enabled: true
    reset_on_reopened:
      enabled: true
    users:
      - marjamis
